# Copyright (c) 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author:  Philippe Sauter <phsauter@iis.ee.ethz.ch>

name: Short Flow

on:
  push:
    branches:
      - '**'

jobs:
  simulation:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Free disk space
        uses: ./.github/actions/free-space
      - name: Run simulation flow in OSEDA
        uses: ./.github/actions/oseda-cmd
        with:
          cmd: ".github/scripts/run_sim_flow.sh"
      - name: Upload built software
        uses: actions/upload-artifact@v4
        with:
          name: croc-sw
          path: sw/bin
      - name: Upload simulation output
        uses: actions/upload-artifact@v4
        with:
          name: simulation-output
          path: |
            verilator/croc.fst
            verilator/croc.log
        continue-on-error: true
      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: verilator/test_*.log
        continue-on-error: true

  synthesis:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Free disk space
        uses: ./.github/actions/free-space
      - name: Run synthesis flow in OSEDA
        uses: ./.github/actions/oseda-cmd
        with:
          cmd: ".github/scripts/run_synth_flow.sh"
      - name: Upload synthesis outputs
        uses: actions/upload-artifact@v4
        with:
          name: croc-synth-reports
          path: |
            yosys/reports
            yosys/out
        continue-on-error: true
